# Common variables for all machines
architecture: "amd64/generic"
domain: "lab"
distro_series: "noble"
main_nic_name: "eno1"  # Default; it will be overwritten in host_vars if necessary

main_nvme_disk_device_name: "nvme0n1"  # Default; it will be overwritten in host_vars if necessary
main_nvme_disk_efi_partition_size: 1

extra_disks: []