#cloud-config
hostname: k8s-m01
manage_etc_hosts: true

# Add your SSH public key
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFXZ9OLEwcxzuMPXYJyhNBDnawJvXCwQZLm28kZ0flxJ guillaume@LP-Guillaume
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILO9kGZmoqzzsSi/l2rbS8uGtPEFD3P5xd5TVi5ejtnj guillaume@PC-Guillaume

# Upgrade all packages on first boot
package_update: true
package_upgrade: true

# (Optional) Install extra packages
packages:
  - lvm2
  - curl
  - htop
  - vim
  - nano
  - git
  - wget
  - net-tools
  - iputils-ping
  - ca-certificates
  - apt-transport-https

runcmd:
  - |
    PV_DEVICE=/dev/nvme0n1p4

    # Create Physical Volume
    echo "Creating PV on $PV_DEVICE"
    pvcreate "$PV_DEVICE"

    # Create Volume Group
    echo "Creating VG on $PV_DEVICE"
    vgcreate vg_cont "$PV_DEVICE"

    # Create Logical Volumes
    echo "Creating LVs on $PV_DEVICE"
    lvcreate -n var_kubelet -L 55G vg_cont
    lvcreate -n var_containerd -L 137G vg_cont

    # Format Logical Volumes
    echo "Formatting LVs"
    mkfs.ext4 /dev/vg_cont/var_kubelet
    mkfs.ext4 /dev/vg_cont/var_containerd

    # Create mount points
    echo "Creating mountpoints"
    mkdir -p /var/lib/kubelet
    mkdir -p /var/lib/containerd

    # Update /etc/fstab
    echo "Edditing fstab"
    echo "/dev/vg_cont/var_kubelet   /var/lib/kubelet ext4    defaults    0 2" >> /etc/fstab
    echo "/dev/vg_cont/var_containerd /var/lib/containerd ext4 defaults  0 2" >> /etc/fstab

    # Mount immediately
    mount -a